### ISSUE TITLE
multiGraphAttention

### ISSUE THREAD

**Issue by zyang-ur** [JeffCHEN2017/WSSTG#4]
Thank you for sharing the repo. I'm having difficulty localizing the ``multiGraphAttention'' file, could you please provide some help? Thanks!

**Comment by zfchenUnique** [comment]
Hi! Thanks for your comment.
Since this repo is extracted from a previous more complicated project and it may contain redundant files or codes. It is unnecessary to run the code with the file. I have deleted that line from the latest version.

**Comment by zyang-ur** [comment]
Thank you for your help :)
In file "vidDataset.py", "extract_position_embedding" from "multiGraphAttention" is called in line 476. Could you please share that function or some examples of the output format?

Thanks a lot.

**Comment by mengliu1991** [comment]
@zyang-ur 
Hi,

Recently, I cannot download the dataset from the link provided by the author. Could you share your downloaded dataset with me? Thank you for your help in advance.
